Repository googleapis/google-api-php-client-services, pull requests merged in 2021-12, with the labels that each got.

#552 Autogenerated update
  src/CloudSearch/Resource/V1.php
  src/HangoutsChat/Resource/Dms.php
  src/HangoutsChat/Resource/DmsConversations.php
  src/HangoutsChat/Resource/Rooms.php
  src/HangoutsChat/Resource/RoomsConversations.php
  src/HangoutsChat/Resource/Spaces.php
  src/HangoutsChat/Resource/SpacesMessages.php
  synth.metadata
Labels: cla: yes, automerge

#553 fix: missing import
  generator/src/googleapis/codegen/languages/php/default/templates/___api_className___.php.tmpl
  generator/tests/testdata/golden/php/default/kitchen_sink.golden
  generator/tests/testdata/golden_discovery/kitchen_sink.json
Labels: cla: yes

#554 chore: switch master to main
  .github/workflows/tests.yml
  tests/VendorTest.php
Labels: cla: yes

#558 Autogenerated update
  src/Bigquery.php
  src/Bigquery/Resource/Tables.php
  src/Dialogflow/GoogleCloudDialogflowCxV3ResponseMessage.php
  src/Dialogflow/GoogleCloudDialogflowCxV3ResponseMessageTelephonyTransferCall.php
  src/Dialogflow/GoogleCloudDialogflowCxV3beta1ResponseMessage.php
  src/Dialogflow/GoogleCloudDialogflowCxV3beta1ResponseMessageTelephonyTransferCall.php
  synth.metadata
Labels: cla: yes, automerge

#559 Autogenerated update
  src/VMMigrationService/AddGroupMigrationResponse.php
  src/VMMigrationService/CancelCloneJobResponse.php
  src/VMMigrationService/CancelCutoverJobResponse.php
  src/VMMigrationService/FinalizeMigrationResponse.php
  src/VMMigrationService/PauseMigrationResponse.php
  src/VMMigrationService/RemoveGroupMigrationResponse.php
  src/VMMigrationService/ResumeMigrationResponse.php
  src/VMMigrationService/StartMigrationResponse.php
  synth.metadata
Labels: cla: yes, automerge

#561 Autogenerated update
  src/Apigee.php
  src/Apigee/GoogleCloudApigeeV1AdjustDeveloperBalanceRequest.php
  src/Apigee/Resource/OrganizationsDevelopersBalance.php
  src/Assuredworkloads/GoogleCloudAssuredworkloadsV1Workload.php
  src/Assuredworkloads/GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponse.php
  src/Assuredworkloads/GoogleCloudAssuredworkloadsV1beta1Workload.php
  src/Assuredworkloads/GoogleCloudAssuredworkloadsV1beta1WorkloadSaaEnrollmentResponse.php
  src/Assuredworkloads/GoogleCloudAssuredworkloadsVersioningV1mainWorkload.php
  src/Assuredworkloads/GoogleCloudAssuredworkloadsVersioningV1mainWorkloadSaaEnrollmentResponse.php
  src/CloudComposer/EnvironmentConfig.php
  src/CloudComposer/MaintenanceWindow.php
  src/CloudFunctions/Resource/ProjectsLocationsFunctions.php
  src/Contactcenterinsights/GoogleCloudContactcenterinsightsV1ExportInsightsDataRequest.php
  src/Contactcenterinsights/GoogleCloudContactcenterinsightsV1alpha1ExportInsightsDataRequest.php
  src/Contactcenterinsights/Resource/ProjectsLocationsConversations.php
  src/DataCatalog.php
  src/DataCatalog/GoogleCloudDatacatalogV1Entry.php
  src/DataCatalog/GoogleCloudDatacatalogV1PersonalDetails.php
  src/DataCatalog/GoogleCloudDatacatalogV1SearchCatalogRequestScope.php
  src/DataCatalog/GoogleCloudDatacatalogV1StarEntryRequest.php
  src/DataCatalog/GoogleCloudDatacatalogV1StarEntryResponse.php
  src/DataCatalog/GoogleCloudDatacatalogV1UnstarEntryRequest.php
  src/DataCatalog/GoogleCloudDatacatalogV1UnstarEntryResponse.php
  src/DataCatalog/Resource/ProjectsLocationsEntryGroupsEntries.php
  src/DisplayVideo/AssignedTargetingOption.php
  src/DisplayVideo/AudioContentTypeAssignedTargetingOptionDetails.php
  src/DisplayVideo/AudioContentTypeTargetingOptionDetails.php
  src/DisplayVideo/Resource/AdvertisersLineItems.php
  src/DisplayVideo/Resource/AdvertisersLineItemsTargetingTypesAssignedTargetingOptions.php
  src/DisplayVideo/TargetingOption.php
  src/Document/GoogleCloudDocumentaiV1DocumentRevision.php
  src/Document/GoogleCloudDocumentaiV1beta1DocumentRevision.php
  src/Document/GoogleCloudDocumentaiV1beta2DocumentRevision.php
  src/Texttospeech/Resource/Voices.php
  synth.metadata
Labels: automerge

#556 Add `@var` to Model Properties to Primitive Types
  generator/src/googleapis/codegen/languages/php/default/templates/___api_className___/___models_className___.php.tmpl
  generator/src/googleapis/codegen/php_generator.py
  generator/src/googleapis/codegen/php_generator_test.py
  generator/tests/testdata/golden/php/default/endpoints_google_owned.golden
  generator/tests/testdata/golden/php/default/endpoints_third_party.golden
  generator/tests/testdata/golden/php/default/kitchen_sink.golden
  generator/tests/testdata/golden/php/default/php_array_scalars.golden
  generator/tests/testdata/golden/php/default/php_float_type.golden
  generator/tests/testdata/golden_discovery/php_array_scalars.json
  generator/tests/testdata/golden_discovery/php_float_type.json
Labels: cla: yes

#565 Autogenerated update
  src/DatabaseMigrationService/CloudSqlSettings.php
  src/DatabaseMigrationService/Resource/ProjectsLocationsConnectionProfiles.php
  src/DatabaseMigrationService/Resource/ProjectsLocationsMigrationJobs.php
  src/Logging/Resource/BillingAccounts.php
  src/Logging/Resource/Folders.php
  src/Logging/Resource/Organizations.php
  src/Logging/Resource/Projects.php
  src/Logging/Resource/V2.php
  src/OSConfig.php
  src/OSConfig/PatchDeployment.php
  src/OSConfig/PausePatchDeploymentRequest.php
  src/OSConfig/Resource/ProjectsPatchDeployments.php
  src/OSConfig/ResumePatchDeploymentRequest.php
  src/Storagetransfer/MetadataOptions.php
  src/Storagetransfer/TransferOptions.php
  src/Storagetransfer/TransferSpec.php
  synth.metadata
Labels: automerge

#567 Autogenerated update
  src/BigtableAdmin/Resource/ProjectsInstances.php
  src/BigtableAdmin/Resource/ProjectsInstancesClusters.php
  src/BigtableAdmin/UndeleteTableMetadata.php
  src/VMMigrationService/ComputeEngineTargetDefaults.php
  src/VMMigrationService/ComputeEngineTargetDetails.php
  synth.metadata
Labels: automerge

#569 Autogenerated update
  src/CloudHealthcare.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasets.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasetsConsentStores.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasetsDicomStores.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasetsFhirStores.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasetsFhirStoresFhir.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasetsHl7V2Stores.php
  src/CloudHealthcare/ValidationConfig.php
  src/CloudSourceRepositories/Resource/ProjectsRepos.php
  src/Datapipelines/Resource/ProjectsLocations.php
  src/Datapipelines/Resource/ProjectsLocationsPipelines.php
  src/Dialogflow/GoogleCloudDialogflowV2beta1KnowledgeOperationMetadata.php
  src/Document/Resource/ProjectsLocations.php
  src/Document/Resource/ProjectsLocationsProcessors.php
  src/Document/Resource/ProjectsLocationsProcessorsProcessorVersions.php
  src/Networkconnectivity/RoutingVPC.php
  src/Spanner/Resource/ProjectsInstancesDatabases.php
  synth.metadata
Labels: automerge

#570 Autogenerated update
  src/Directory/Resource/Chromeosdevices.php
  src/Directory/Resource/Orgunits.php
  synth.metadata
Labels: automerge

#572 Autogenerated update
  src/CloudHealthcare.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasets.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasetsConsentStores.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasetsDicomStores.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasetsFhirStores.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasetsFhirStoresFhir.php
  src/CloudHealthcare/Resource/ProjectsLocationsDatasetsHl7V2Stores.php
  src/CloudHealthcare/ValidationConfig.php
  src/Dns.php
  src/Dns/Resource/ResponsePolicies.php
  src/Dns/Resource/ResponsePolicyRules.php
  src/Dns/ResponsePoliciesListResponse.php
  src/Dns/ResponsePoliciesPatchResponse.php
  src/Dns/ResponsePoliciesUpdateResponse.php
  src/Dns/ResponsePolicy.php
  src/Dns/ResponsePolicyNetwork.php
  src/Dns/ResponsePolicyRule.php
  src/Dns/ResponsePolicyRuleLocalData.php
  src/Dns/ResponsePolicyRulesListResponse.php
  src/Dns/ResponsePolicyRulesPatchResponse.php
  src/Dns/ResponsePolicyRulesUpdateResponse.php
  synth.metadata
Labels: automerge

#573 Autogenerated update
  src/CloudDeploy/Rollout.php
  src/CloudDeploy/TargetRender.php
  synth.metadata
Labels: automerge

#574 Autogenerated update
  src/AlertCenter/AppsOutage.php
  src/AlertCenter/MergeInfo.php
  synth.metadata
Labels: automerge
